<table id="dgPerfiles" title="Perfiles" style="width:700px;height:250px"
        toolbar="#toolbar" pagination="true" idField="idPerfil"
        rownumbers="true" fitColumns="true" singleSelect="true">
    <thead>
        <tr>
            <th field="nombre" editor="{type:'validatebox',options:{required:true}}">Perfil</th>            
        </tr>
    </thead>
</table>
<div id="toolbar">
    <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="javascript:$('#dgPerfiles').edatagrid('addRow')">Nuevo</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="javascript:$('#dgPerfiles').edatagrid('destroyRow')">Eliminar</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-save" plain="true" onclick="javascript:$('#dgPerfiles').edatagrid('saveRow')">Guarda</a>
    <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-undo" plain="true" onclick="javascript:$('#dgPerfiles').edatagrid('cancelRow')">Cancelar</a>
</div>
<script type="text/javascript">
$(function(){
	var dg = $('#dgPerfiles').edatagrid({
	    url: '<?php echo $this->url('catalogos/default', array('controller' => 'perfiles','action' => 'listado')); ?>',
	    saveUrl: '<?php echo $this->url('catalogos/default', array('controller' => 'perfiles','action' => 'guarda')); ?>',
	    updateUrl: '<?php echo $this->url('catalogos/default', array('controller' => 'perfiles','action' => 'actualiza')); ?>',
	    destroyUrl: '<?php echo $this->url('catalogos/default', array('controller' => 'perfiles','action' => 'elimina')); ?>',
	    filterBtnIconCls:'icon-filter',
	    remoteFilter:true,
	    onError: function(index,row){
			$.messager.alert('Error',row.msg,'error');
		},
		destroyMsg:{
			norecord:{	// when no record is selected
				title:'Precausion',
				msg:'No selecciono ningun registro.'
			},
			confirm:{	// when select a row
				title:'Confirmacion',
				msg:'Estas seguro que quieres borrarlo?'
			}
		}
	});
	dg.edatagrid('enableFilter');

	
});
</script>
