<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sistema\Module'                        => __DIR__ . '/Module.php',
    'Sistema\Controller\SistemaController' => __DIR__ . '/src/Sistema/Controller/SistemaController.php',
    'SistemaTest\Framework\TestCase'        => __DIR__ . '/tests/Sistema/Framework/TestCase.php',
    'SistemaTest\SampleTest'                => __DIR__ . '/tests/Sistema/SampleTest.php',
);
