<style>

</style>
<div style="margin:20px 0;"></div>
<div class="easyui-layout" style="width:100%;height:600px;">
    <!-- <div data-options="region:'north'" style="height:50px">
       
    </div>
    <div data-options="region:'south',split:true" style="height:50px;"></div> -->
    <div data-options="region:'east',split:true" title="<?php echo $this->tipoPerfil;?>" style="width:130px;">
         <img alt="" src="<?php echo $this->basepath('img/msn.gif');?>"><br>
        <p><?php echo $this->nombreCompleto;?></p>
    </div>
    <!-- <div data-options="region:'west',split:true" title="<?php echo $this->tipoPerfil;?>" style="width:160px;">        
    </div>-->
    <div data-options="region:'center',iconCls:'icon-ok'" title="Center">
         <div id="nav">
            <?php echo $this->menu;?>
        </div> 
    </div>
</div>