<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Facturacion Electronica') ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/jquery-easyui/themes/default/easyui.css')
                        ->prependStylesheet($this->basePath() . '/jquery-easyui/themes/icon.css')
                        ->prependStylesheet($this->basePath() . '/jquery-easyui/themes/color.css')
                        ->prependStylesheet($this->basePath() . '/css/menu.css')
                         ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/jquery-easyui/locale/easyui-lang-es.js')
                                      ->prependFile($this->basePath() . '/jquery-easyui/plugins/datagrid-filter.js')
                                      ->prependFile($this->basePath() . '/jquery-easyui/jquery.easyui.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-2.1.3.min.js') ?>

    </head>
    <body>
        <?php echo $this->content; ?>        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
