<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Catalogos\Module'                        => __DIR__ . '/Module.php',
    'Catalogos\Controller\CatalogosController' => __DIR__ . '/src/Catalogos/Controller/CatalogosController.php',
    'CatalogosTest\Framework\TestCase'        => __DIR__ . '/tests/Catalogos/Framework/TestCase.php',
    'CatalogosTest\SampleTest'                => __DIR__ . '/tests/Catalogos/SampleTest.php',
);
